### ISSUE TITLE
Chapter 2, exercise 10 (10.md) problems.

### ISSUE THREAD

**Issue by Spork-Schivago** [hiberno/c-programming-a-modern-approach#1]
Hi,

The question in Chapter 2, exercise 10 (file 10.md), asks which white spaces are essential.   I believe there are some mistakes in 10.md.    For example, the space between return and 0 are essential.   With return0, the compiler should error out.   It needs to be return 0; or return(0);   In the original code though, the statement is return 0;, therefore, I believe the space is essential.

Also, for the string literals, they can be considered essential as well, because if you remove the spaces between them, it changes the program.   For example,
```
printf("Dimensions: %dx%dx%d\n", length, width, height);
printf("Volume (cubic inches): %d\n", volume);
```
will print
```
Dimensions: 12x10x8
Volume (cubic inches): 960
```
However, if you remove the spaces, like:
```
printf("Dimensions:%dx%dx%d\n", length, width, height);
printf("Volume(cubicinches):%d\n", volume);
```
You get the following output
```
Dimensions:12x10x8
Volume(cubicinches):960
```
Essentially, it's a different program, not by much, but I believe the question is asking what spaces are required in order to not change the program and get it to compile successfully.    The book does mention how if yo remove the spaces in a string literal, you change that string literal.   I think the question should be a bit more clear in this sense but I personally believe, those spaces are required as well.    Just thought you'd like to know.

**Comment by hiberno** [comment]
> therefore, I believe the space is essential.

You are right, I guess. 


> Just thought you'd like to know.

Thank you very much. 

I should probably continue working through that book or remove that repo from here ;)

**Comment by Spork-Schivago** [comment]
I personally found your repo very helpful.   I'm not a student or anything and I'm trying to learn on my own.   Although the author does provide answers to some of the questions, because this book is used in certain colleges I believe, he doesn't provide all the answers.  It's nice to be able to come here and check to see how my answers compare to someone else's.   Thanks!

**Comment by hiberno** [comment]
Happy that you found it helpful :) I'll leave it online and maybe even continue updating it.
